spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_wines?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: spring
    password: aqwserft234252
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
image:
  location: C:\Users\rtl1e\IdeaProjects\WineReviews\backend\images